# Generated by Django 4.1.7 on 2023-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.CharField(max_length=50)),
                ('reserva', models.BooleanField(default=False)),
            ],
        ),
    ]
