# Generated by Django 4.1.7 on 2023-09-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_turno_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
    ]
